name: pokeapi_dart_wrapper
description: A Dart wrapper for PokeApi
version: 0.1.1
homepage: https://github.com/pongloongyeat/pokeapi_dart_wrapper

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  freezed_annotation: ^2.0.3
  recase: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.11
  coverage: ^1.1.0
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  pretty_dio_logger: ^1.1.1
  test: ^1.19.2
  very_good_analysis: ^3.0.0
